Corrige, teoricamente, mostrar foto de perfil no SDDM
gelos-icmc/infra pull request #9
Opened 2024-09-16 20:35 UTC by LuNeder

2024-09-16 21:17 UTC, Misterio77 commented
Sem gelos entitty pelo amor de deus HEUAUEAH

2024-09-16 21:17 UTC, Misterio77 requested changes

2024-09-16 21:17 UTC, Misterio77 commented on hosts/common/desktop-salinha.nix
> +        touch "$i/CHEETOFLAMINGHOTDILDO.mp3"
q

2024-09-16 21:18 UTC, LuNeder commented
> Sem gelos entitty pelo amor de deus HEUAUEAH

Que

2024-09-16 21:19 UTC, Misterio77 commented
> Que

O autor do commit tava gelos entity heuaheua, daí arrumei e dei push

2024-09-16 21:20 UTC, LuNeder commented on hosts/common/desktop-salinha.nix
> +        touch "$i/CHEETOFLAMINGHOTDILDO.mp3"
O Furry :)

(eu tinha posto “placeholder”, pq o script falha em expandir o $j/* se não existe nenhuma file na home da pessoa (não falha em expandir, mas o chmod procura um arquivo inexistente chamado “*”) então se n tem files nela precisa criar um placeholder. O Furry sugeriu o nome supracitado, por ser mais criativo.)

2024-09-16 21:22 UTC, LuNeder commented
> > Que
> 
> O autor do commit tava gelos entity heuaheua, daí arrumei e dei push

Ah, é pq ta na home do GELOS entity a repo e eu n queria botar meu email no git dessa conta kskakakskaksks

2024-09-16 21:28 UTC, Misterio77 commented
Mas enfim, sobre a change:

Eu _realmente_ não gosto muito dessa approach. Isso n só muta a permissão da home do usuário, como tb muta das pastas _dentro dela_.

O certo seria a gente:
- Setar `users.users.<name>.homeMode` pra defaultar pra 711 (`rwx --x --x`). Assim as homes ficam legíveis por padrão, e cada um pode setar a sua própria pra 700 (`rwx --- ---`) se preferir.
- Pra proteger os arquivos da home, a gente seta a `umask` pra algo tipo `077` (faz as coisas criadas terem `rwx --- ---` por padrao) ou `027` (faz coisas terem `rwx r-x ---`). Hj provavelmente tá `022` (que faz ter `rwx r-x r-x` por padrão).

2024-09-16 21:33 UTC, LuNeder commented
> * Setar `users.users.<name>.homeMode`

O problema é que aí tem q sempre fazer um por um né
(e que o .face não vai ser criado 711 automaticamente, inclusive acho que faltou no script a parte de setar o .face pra 711)

2024-09-16 21:52 UTC, Misterio77 commented
> O problema é que aí tem q sempre fazer um por um né

Nono, dá pra trocar o default. Como o padrão já usa `mkDefault` (1000), é só setar com prioridade 999. Pra fazer isso em coisa nestada (vulgo `<name>`), basta vc entrar dentro da declaração do submodulo. Assim:

```nix
{ lib, ... }: {
  options.users.users = lib.mkOption {
    type = lib.types.attrsOf (lib.types.submodule {
      homeMode = lib.mkOverride 999 "711";
    });
  };
}
```

2024-09-16 21:56 UTC, Misterio77 commented
> E que o .face não vai ser criado 711 automaticamente

A gente pode usar `systemd.user.tmpfiles.rules` pra criar um .profile que vem setado em 711. Ou fazer uma systemd user unit que copia um default em 711 pra home deles qd ela é criada.

2024-09-16 22:05 UTC, Misterio77 commented
Btw o SDDM já lê por padrão `/var/lib/AccountsService/icons/usuario.face.icon`, talvez seria uma possibilidade tb.

2024-09-23 18:22 UTC, closed without merging

2024-09-23 18:22 UTC, LuNeder commented
Aparentemente eu que tava fazendo merda e funciona mesmo sem isso